# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2bLxpS6RzU6DiL8KFDZQa9iM9TCdvLM
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import time
from IPython.display import clear_output

def get_live_data(ticker="AAPL", period="1d", interval="1m"):
    data = yf.download(ticker, period=period, interval=interval, progress=False)
    return data

ticker = "AAPL"

for i in range(10):
    clear_output(wait=True)
    df = get_live_data(ticker)

    plt.figure(figsize=(10,5))
    plt.plot(df.index, df['Close'], label=f"{ticker} Price", color='blue')
    plt.title(f"Live Stock Price - {ticker}")
    plt.xlabel("Time")
    plt.ylabel("Price (USD)")
    plt.legend()
    plt.grid(True)
    plt.show()

    print(f"Last Price: {float(df['Close'].iloc[-1]):.2f}")
    time.sleep(30)
    from sklearn.linear_model import LinearRegression
import numpy as np

df = get_live_data(ticker)
df = df.reset_index()
df['time_index'] = np.arange(len(df))

X = df[['time_index']]
y = df['Close']

model = LinearRegression()
model.fit(X, y)

next_index = np.array([[len(df)]])
predicted_price = model.predict(next_index)

print(f"Predicted next price for {ticker}: {float(predicted_price[0]):.2f}")